default:
  base_dir: "/etc/edgemesh"
  config_file: "/etc/edgemesh/config-file"
  edgemesh_agent_config_name: "edgemesh-agent.yaml"
  edgemesh_gateway_config_name: "edgemesh-gateway.yaml"

  edgemesh_dns_module_name: "EdgeDNS"
  edgemesh_proxy_module_name: "EdgeProxy"
  edgemesh_gateway_module_name: "EdgeGateway"
  edgemesh_tunnel_module_name: "EdgeTunnel"
  edgemesh_cni_module_name: "EdgeCNI"

  bridge_device_name: "edgemesh0"
  bridge_device_ip: "169.254.96.16"
  tun_device_name: "edge_tun0"

  temp_kube_config_path: "kubeconfig"
  temp_core_file_path: "corefile"
  meta_server_address: "http://127.0.0.1:10550"
  meta_server_cert_dir: "/etc/edgemesh/metaserver/"
  meta_server_ca_file: "/etc/edgemesh/metaserver/rootCA.crt"
  meta_server_cert_file: "/etc/edgemesh/metaserver/server.crt"
  meta_server_key_file: "/etc/edgemesh/metaserver/server.key"

  edge_mode: "EdgeMode"
  edge_mode_enable: true
  cloud_mode: "CloudMode"
  manual_mode: "ManualMode"
  kubeapi:
    master: "https://127.0.0.1:6443"
    content_type: "application/json"
    qps: 50
    burst: 100
    kube_config: "~/.kube/config"
    meta_server: null
    delete_kube_config: false
  edge_dns:
    enable: true
    listen_interface: "0.0.0.0"
    listen_port: 50
    kubernetes_plugin_enable: true
    kubernetes_api_server: "0.0.0.0"
    kubernetes_ttl: 2
  cache_dns:
    enable: true
    auto_detect: true
    upstream_servers:
    - "8.8.8.8"
    - "8.8.4.4"
    cache_ttl: 20
  edgeCNI:
    enable: true
    encap_ip: "192.168.1.1"
    tun_mode: 0
    mesh_cidr_config: null

  empty_node_name: "EMPTY_NODE_NAME"
  empty_pod_name: "EMPTY_POD_NAME"
  service_filter_mode:
    filter_if_label_exists_mode: "FilterIfLabelExists"
    filter_if_label_doesn_not_exists_mode: "FilterIfLabelDoesNotExists"
  loadbalancer_caller:
    proxy_caller: "ProxyCaller"
    gateway_caller: "GatewayCaller"
  discovery_type:
    mdns_discovery: "MDNS"
    dht_discovery: "DHT"

v1:
  base_dir: "/etc/edgemesh"
  config_file: "/etc/edgemesh/config-file"
  edgemesh_agent_config_name: "edgemesh-agent.yaml"
  edgemesh_gateway_config_name: "edgemesh-gateway.yaml"

  edgemesh_dns_module_name: "EdgeDNS"
  edgemesh_proxy_module_name: "EdgeProxy"
  edgemesh_gateway_module_name: "EdgeGateway"
  edgemesh_tunnel_module_name: "EdgeTunnel"
  edgemesh_cni_module_name: "EdgeCNI"

  bridge_device_name: "edgemesh0"
  bridge_device_ip: ""
  tun_device_name: "edge_tun0"

  temp_kube_config_path: "kubeconfig"
  temp_core_file_path: "corefile"
  meta_server_address: "http://127.0.0.1:10550"
  meta_server_cert_dir: "/etc/edgemesh/metaserver/"
  meta_server_ca_file: "/etc/edgemesh/metaserver/rootCA.crt"
  meta_server_cert_file: "/etc/edgemesh/metaserver/server.crt"
  meta_server_key_file: "/etc/edgemesh/metaserver/server.key"

  edge_mode: "EdgeModev1"
  edge_mode_enable: true
  cloud_mode: "CloudModev1"
  manual_mode: "ManualModev1"
  kubernetes_plugin_enable: true

  empty_node_name: "EMPTY_NODE_NAME"
  empty_pod_name: "EMPTY_POD_NAME"
  service_filter_mode:
    filter_if_label_exists_mode: "FilterIfLabelExists"
    filter_if_label_doesn_not_exists_mode: "FilterIfLabelDoesNotExists"
  loadbalancer_caller:
    proxy_caller: "ProxyCaller"
    gateway_caller: "GatewayCaller"
  discovery_type:
    mdns_discovery: "MDNS"
    dht_discovery: "DHT"
