[package]
name = "cortexflow-metrics"
version = "0.1.0"
edition = "2024"
description = "Cortexflow metrics service library"
license = "Apache-2.0"
readme = "../../../../README.md"
documentation = "https://docs.cortexflow.org"
homepage = "https://docs.cortexflow.org"
repository = "https://github.com/CortexFlow/CortexBrain"

[dependencies]
aya = "0.13.1"
aya-log = "0.2.1"
bytes = "1.4"
tokio = { version = "1.48.0", features = [
    "rt",
    "macros",
    "time",
    "fs",
    "signal",
    "rt-multi-thread",
    "sync"
] }
anyhow = "1.0"
tracing = "0.1.41"
tracing-subscriber = { version = "0.3.19", features = ["env-filter"] }
libc = "0.2.172"
bytemuck = "1.23.0"
cortexbrain-common = { path = "../../../common/", features = [
    "map-handlers",
    "program-handlers",
    "buffer-reader",
    "monitoring-structs",
    "network-structs"
] }
nix = { version = "0.30.1", features = ["net"] }
opentelemetry = "0.32.0"
opentelemetry_sdk = "0.32.0"
opentelemetry-otlp = { version = "0.32.0", features = ["grpc-tonic"] }
