apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortexflow-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: lorenzotettamanti/cortexflow-client:latest
        env:
        - name: CONFIG_PATH
          value: "/usr/src/cortexbrain-client/config.yaml"
        volumeMounts:
        - name: config-volume
          mountPath: /etc/config
      volumes:
      - name: config-volume
        configMap:
          name: cortexbrain-client-config
