apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: coredns-editor-binding
subjects:
- kind: ServiceAccount
  name: default
  namespace: cortexflow
roleRef:
  kind: ClusterRole
  name: coredns-editor
  apiGroup: rbac.authorization.k8s.io
