apiVersion: v1
kind: Pod
metadata:
  name: test-proxy
  namespace: cortexflow
  labels:
    proxy-injection: enabled
  annotations:
    proxy-injection: enabled
spec:
  containers:
  - name: nginx
    image: nginx
