apiVersion: v1
kind: ServiceAccount
metadata:
  name: testing-service-account
  namespace: cortexflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-discovery-role
  namespace: cortexflow
rules:
- apiGroups: [ "" ]
  resources: [ "services", "pods" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "" ]
  resources: [ "configmaps" ]
  verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-discovery-role-binding
  namespace: cortexflow
subjects:
- kind: ServiceAccount
  name: testing-service-account
  namespace: cortexflow
roleRef:
  kind: Role
  name: service-discovery-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
  namespace: cortexflow
  labels:
    app: test1
spec:
  serviceAccountName: testing-service-account
  containers:
  - name: test-pod
    image: nicolaka/netshoot
    command: ["/bin/bash", "-c", "sleep 3600"]
    ports:
    - containerPort: 5053
      protocol: UDP
    - containerPort: 5054
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod2
  namespace: cortexflow
  labels:
    app: test2
spec:
  serviceAccountName: testing-service-account
  containers:
  - name: test-pod2
    image: nicolaka/netshoot
    command: ["/bin/bash", "-c", "sleep 3600"]
    ports:
    - containerPort: 5053
      protocol: UDP
    - containerPort: 5054
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod3
  namespace: cortexflow
  labels:
    app: test3
spec:
  serviceAccountName: testing-service-account
  containers:
  - name: test-pod3
    image: nicolaka/netshoot
    command: ["/bin/bash", "-c", "sleep 3600"]
    ports:
    - containerPort: 5053
      protocol: UDP
    - containerPort: 5054
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: test-pod
  namespace: cortexflow
spec:
  selector:
    app: test1
  ports:
  - protocol: TCP
    name: tcp-connection
    port: 5054
    targetPort: 5054
  - protocol: UDP
    name: udp-connection
    port: 5053
    targetPort: 5053
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: test-pod2
  namespace: cortexflow
spec:
  selector:
    app: test2
  ports:
  - protocol: TCP
    name: tcp-connection
    port: 5054
    targetPort: 5054
  - protocol: UDP
    name: udp-connection
    port: 5053
    targetPort: 5053
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: test-pod3
  namespace: cortexflow
spec:
  selector:
    app: test3
  ports:
  - protocol: TCP
    name: tcp-connection
    port: 5054
    targetPort: 5054
  - protocol: UDP
    name: udp-connection
    port: 5053
    targetPort: 5053
  type: ClusterIP
