apiVersion: v1
kind: ServiceAccount
metadata:
  name: proxy-service-account
  namespace: cortexflow
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: service-discovery-role
  namespace: cortexflow
rules:
- apiGroups: [ "" ]
  resources: [ "services", "pods" ]
  verbs: [ "get", "list", "watch" ]
- apiGroups: [ "" ]
  resources: [ "configmaps" ]
  verbs: [ "get", "list", "watch" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: service-discovery-role-binding
  namespace: cortexflow
subjects:
- kind: ServiceAccount
  name: proxy-service-account
  namespace: cortexflow
roleRef:
  kind: Role
  name: service-discovery-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: test-proxy
  namespace: cortexflow
  labels:
    app: test-proxy
    proxy-injection: enabled
  annotations:
    proxy-injection: enabled
spec:
  serviceAccountName: proxy-service-account
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 5053 # Porta UDP
      protocol: UDP
    - containerPort: 5054 # Porta TCP
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: test-proxy
  namespace: cortexflow
spec:
  selector:
    app: test-proxy # Deve corrispondere alla label del pod
  ports:
  - protocol: TCP
    name: tcp-connection
    port: 5054
    targetPort: 5054
  - protocol: UDP
    name: udp-connection
    port: 5053
    targetPort: 5053
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  name: test-proxy2
  namespace: cortexflow
  labels:
    app: test-proxy2
    proxy-injection: enabled
  annotations:
    proxy-injection: enabled
spec:
  serviceAccountName: proxy-service-account
  containers:
  - name: nginx
    image: nginx
    ports:
    - containerPort: 5053
      protocol: UDP
    - containerPort: 5054
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: test-proxy2
  namespace: cortexflow
spec:
  selector:
    app: test-proxy2 # Deve corrispondere alla label del pod
  ports:
  - protocol: TCP
    name: tcp-connection
    port: 5054
    targetPort: 5054
  - protocol: UDP
    name: udp-connection
    port: 5053
    targetPort: 5053
  type: ClusterIP
