apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortexflow-dns
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: custom-dns
  template:
    metadata:
      labels:
        app: custom-dns
    spec:
      containers:
      - name: dns-server
        image: lorenzotettamanti/cortexflow-kernel:latest
        command: [ "tail", "-f", "/dev/null" ]
        ports:
        - containerPort: 53
          protocol: UDP
        - containerPort: 8080
          protocol: TCP
        volumeMounts:
        - name: dns-config
          mountPath: /etc/dns
      volumes:
      - name: dns-config
        configMap:
          name: cortexbrain-client-config
---
apiVersion: v1
kind: Service
metadata:
  name: cortexflow-dns-service
  namespace: default
spec:
  selector:
    app: custom-dns
  ports:
  - name: dns-udp
    protocol: UDP
    port: 53
    targetPort: 53
  - name: api-tcp
    protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP
