apiVersion: apps/v1
kind: Deployment
metadata:
  name: cortexflow-proxy
  labels:
    app: cortexflow-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cortexflow-proxy
  template:
    metadata:
      labels:
        app: cortexflow-proxy
    spec:
      containers:
      - name: proxy-sidecar
        image: lorenzotettamanti/cortexflow-proxy:0.0.1
        command: [ "tail", "-f", "/dev/null" ]
        ports:
        - containerPort: 9090
        env:
        - name: DNS_SERVER_HOST
          value: "dns-service.default.svc.cluster.local:53"
        volumeMounts:
        - name: proxy-config
          mountPath: /etc/proxy

      volumes:
      - name: proxy-config
        configMap:
          name: proxy-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy-config
data:
  proxy.yaml: |
    log_level: "info"
    metrics_path: "/metrics"
    listen_address: "0.0.0.0"
    listen_port: 9090
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-service
  labels:
    app: cortexflow-proxy
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 9090
    protocol: TCP
  selector:
    app: cortexflow-proxy
