apiVersion: v1
kind: Secret
metadata:
  name: proxy-injector-tls
  namespace: cortexflow
type: kubernetes.io/tls
data:
  tls.crt: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURYakNDQWthZ0F3SUJBZ0lRSmczL3pnbFVKcFVZU2FXOEM4S29uekFOQmdrcWhraUc5dzBCQVFzRkFEQVYKTVJNd0VRWURWUVFLRXdwamIzSjBaWGhtYkc5M01CNFhEVEkxTURNeE5URXpORGswTVZvWERUSTJNRE14TlRFegpORGswTVZvd0ZURVRNQkVHQTFVRUNoTUtZMjl5ZEdWNFpteHZkekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFECmdnRVBBRENDQVFvQ2dnRUJBTUM2c0NBc1I3WnZSV2VTeHkwUVJma3NwWWt2Tm9EdElQWXBkcU1XMGl5MDNaWHkKYjBsUktkaWZnSnQwWGswTVk2Uk1CckRSdXRSL282K09zRmtkT0VuU1J3T2hPc0ZXdk4rSkxMNnAxRndZTnR2RQphOHI3SHpRNlRlbkQ4bXdYVTlhL2ozVCt5dktmY0hvYUdManpjeGFOTUhjVW5rN1IwWloxUk9TK0dCMDIyd2hSCmorL3lEZWFlVDRsWUVTNGYwbFdFaDQ1N0FJc1pNRlh1cUNPcjhkWlhncWtGcFUrWDFzaWsyYjBwYjZ3ZGE3bVcKNW5vNXRmQ0FrVkgzbnpCbGNKZWhGUDFueXpGNzJhSW5ZajRzVnFhMmdJVHIvRG1GVTZRRHZvdldsZFJiWXIySQpweit2M3pSUzZWUVI2MTNxNTdOM3RMZ21xRnZwcTQxRHYzb1VHeXNDQXdFQUFhT0JxVENCcGpBVEJnTlZIU1VFCkREQUtCZ2dyQmdFRkJRY0RBVEFNQmdOVkhSTUJBZjhFQWpBQU1JR0FCZ05WSFJFRWVUQjNnZzV3Y205NGVTMXAKYm1wbFkzUnZjb0laY0hKdmVIa3RhVzVxWldOMGIzSXVZMjl5ZEdWNFpteHZkNElkY0hKdmVIa3RhVzVxWldOMApiM0l1WTI5eWRHVjRabXh2ZHk1emRtT0NLM0J5YjNoNUxXbHVhbVZqZEc5eUxtTnZjblJsZUdac2IzY3VjM1pqCkxtTnNkWE4wWlhJdWJHOWpZV3d3RFFZSktvWklodmNOQVFFTEJRQURnZ0VCQUJmRGhmVFVpVFlTSWpxN280T2IKR3pGdW9iQzg3dkNDTk54VWE5NCtTcFhHOS9sQnJvWmc4Ukd2eUhpRUZtZHBuZ3dhMksycENZSDlKYzRnRWpOdApJa253eHhCSitkOHlVSUN3WlNJR0VudWx2T0R4V1NtRHJXR1JWbjVCZ0VuTURBb0sxWXBiVDkrSVcwYmFVb1I5Ck5ubW1veEUyRHE2MU05azVBRlY2NFpuSktLWHZ0NjR5Unh0WDJVSnBmNFdxVkV6aGprODFYTzVKaGtVdDJ1cGgKbS9oS3JXZjNIWjVPbDVNUXBvYnYrVGFEejdhbzVSdEtpVURyd2kwK09XMjBhc1NQMUJtV2NvdFBtQ3lnN0ZBTgpsakZ0TURxZ25zb2F3NGFmS0czeTlGNWhodzdvVFRMWlpuSkVFUWhuNWNoMkk3YnNSVkF1eTU4UThMb0lKSXlMCnRqND0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
  tls.key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBd0xxd0lDeEh0bTlGWjVMSExSQkYrU3lsaVM4MmdPMGc5aWwyb3hiU0xMVGRsZkp2ClNWRXAySitBbTNSZVRReGpwRXdHc05HNjFIK2pyNDZ3V1IwNFNkSkhBNkU2d1ZhODM0a3N2cW5VWEJnMjI4UnIKeXZzZk5EcE42Y1B5YkJkVDFyK1BkUDdLOHA5d2Vob1l1UE56Rm8wd2R4U2VUdEhSbG5WRTVMNFlIVGJiQ0ZHUAo3L0lONXA1UGlWZ1JMaC9TVllTSGpuc0FpeGt3VmU2b0k2dngxbGVDcVFXbFQ1Zld5S1RadlNsdnJCMXJ1WmJtCmVqbTE4SUNSVWZlZk1HVndsNkVVL1dmTE1YdlpvaWRpUGl4V3ByYUFoT3Y4T1lWVHBBTytpOWFWMUZ0aXZZaW4KUDYvZk5GTHBWQkhyWGVybnMzZTB1Q2FvVyttcmpVTy9laFFiS3dJREFRQUJBb0lCQUYzc0hOenc5MW0rekRIMwpZNzFnU3RsdG1wWktQZU9DckNlS2VWaHRUS3VnME1POFMrT00vRG1uTVlPUXFFd2dGNGIvemRycHVvVElWenE4CjdNL2czNGVLUkRWT28xV0pNYTQyS1dvWlZYWTBEcmYyOXhrS1hHQ1ZjVmJVdVJWWUlQRnNsVHJNMkpaNGdOWGcKVmQvOE5EL3ZPb2t0c1NCMFBCRjR3TVJBcDN2RVlQYlgxODdHTVVleldsN0lxM2FpU2RtNkdJT0dpZmJSYkxzdAp0cThMOXhFNU1tWU10cklEWWpVZlVBZ3BGdUJzNk9CZy9UcVN1Y1lBOVFWN2lGQzJibmFBSWZ0dEdmNXJ6NzNFCnQ5RnZGQlcxN0lGQ0pzbGZhUnIvMXdJNDRtaDJvUks5ZlVLbXBXUzhDUFpyNVdNYUFXcDUrZUdWZFZDMWpJR2oKU216WjVRRUNnWUVBN0t4bkQ0SWRGTVY1RUNEZlF1Ny9ZRWZ3K09rVU4rNkdJUU9tYlo2Z3ZKVE9uc3l6a2FUTQo0SWRGSzlmaWhwdVhFZWxLK0dhWU1lWXpVYlYyT0JsT21jK2dIaENJMzgwaUxtYUZ6STRhbHNDVFBEL2o5aEF3CmxyU0VuQ0FZeWtNcnl1eDNzR2xvdWRvOUdjb3pubXllMjROZmxMKzFPYkhlektnZ21sdEg1RUVDZ1lFQTBIZWsKcm1LWUdsQ0xWVG1yUE1VeVROeGdwQUNrVUovUlQrUENyTWh5L2dEaEhLNUZQdm90a1RVaFByMlBIenpGc2ZWSQpCWVNCaC9JclRYRlFPSlVGOHVpR3FPTzlqQ2ZCSWMxUldrSm80ZHpLcFM4WWVMa2s0YWpPMzNWb3NuL3h0NFBmClNMREVGM1U2K1I2VTVWZUVGb3BCL3NIMWRQYU5RZkVFbHR3S3RHc0NnWUFlTlY4dU5wQlpyMTdsZFJ5cUlYRk4KSzhHUk04YlY0TWNUL2JCSGU2RE9rVHZTUHhTSWVYMkJCeU1JRnBVZVUwdTBDSS8rSnJJMFpFcVdtay9ObDBWVwpFbzlBWnlIaFZ3Q081WjBjWCtMNjdQZWVFQldidWJOSitSNllBdXpISEUzQnArOGJBRWxTdDQxbTlrMGlZb0RnClNlTndUQXZvb2xCcTFPYmNiTncvUVFLQmdRREcxZWNvUVhnTVdWaWNZRlg0cjZucmI2TnBxZ2NQczIva2dEd1YKcTFjcStGRytsbVlMekhtYjc0NFhGcHlsVWNUS21VWXBwUm9iUFp1WjBRT1FCR3ZaSlhvVEtxMkhPZi9YS3N0MgppTE1iQXdueUJmcVVZeHRQZFVCa0dNdFV2ZjRpYU5DV3Q2dEJLSnFvTkVnV2U2UE1EL0VrZVlHU0h2dmFzblVMCkl6Tytvd0tCZ0d0KzB6cnhjdC9rQ0RXUjdiek1tWkVadXVmR0RyVUR2bEtYWDU5cWpRSmpiVC9OS2MzaFZRL2sKdWFqTGdFN2J2dWM4Q0ZqRVROUW0vZ1RWaVFITTFKN1BaMFFiTThkRC9tcWRQbWNPb2E1eDYydzBXSDZnNVo2RApycFJ3T3BDR1NNMGpsMHZiWXJWdm1sbHlZVnVpU2owNjNBeXBLT1VxV3dSVE93dWhvSUpECi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
---
apiVersion: v1
kind: Service
metadata:
  name: proxy-injector
  namespace: cortexflow
spec:
  ports:
  - port: 443
    targetPort: 9443
  selector:
    app: proxy-injector
---
apiVersion: v1
kind: Pod
metadata:
  name: proxy-injector
  namespace: cortexflow
  labels:
    app: proxy-injector
spec:
  containers:
  - name: proxy-injector
    image: lorenzotettamanti/cortexflow-proxy-injector:latest
    ports:
    - containerPort: 9443
    volumeMounts:
    - name: webhook-certs
      mountPath: /etc/webhook/certs
      readOnly: true
  volumes:
  - name: webhook-certs
    secret:
      secretName: proxy-injector-tls
