# service-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: cortexflow
  name: service-reader
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["get", "list", "watch"]
---
# service-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-services
  namespace: cortexflow
subjects:
- kind: ServiceAccount
  name: default
  namespace: cortexflow
roleRef:
  kind: Role
  name: service-reader
  apiGroup: rbac.authorization.k8s.io
