[package]
name = "xtask"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.46", features = ["derive"] }
aya-tool = { git = "https://github.com/aya-rs/aya" }
anyhow = "1.0.99"
