name: Update documentation

on: 
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pip'

      - name: Install mkdocs
        run: |
          pip install mkdocs mkdocs-material

      - name: Build documentation
        run: mkdocs build
        working-directory: ./Doc

      - name: Deploy to site host
        uses: airvzxf/ftp-deployment-action@latest
        with:
          server: ${{ secrets.SFTP_SERVER }}
          user: ${{ secrets.SFTP_USERNAME }}
          password: ${{ secrets.SFTP_PSW }}
          local_dir: './site'
          remote_dir: ${{ secrets.CF_SITE_DIR }}
